#  grants list namespaces permissions to the presto service account
{{- if .Values.presto.spec.config.connectors.prometheus.enabled }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace }}-presto-service-account
rules:
  - apiGroups: ["metering.openshift.io"]
    resources:
      - namespaces
    verbs:
      - list

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: presto
  labels:
    app: presto
roleRef:
  kind: ClusterRole
  name: {{ .Release.Namespace }}-presto-service-account
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: presto
    namespace: {{ .Release.Namespace }}
{{- end }}
